<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="header.css">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
	</head>
    <body background="img/back-jeux.jpg" >	
		
		 <nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <a class="navbar-brand" href="accueil">MegaGame</a>
			</div>
			<ul class="nav navbar-nav">
			  <li class="active"><a  href="accueil">Accueil</a></li>
			  <li class="ul-barre"><a href="jeux_page1">Jeux</a></li>
			  <li class="ul-barre"><a href="ajout_jeu">Ajouter</a></li>
			  
			   <li class="ul-barre"><a class="ul-barre" href="panier_jeux" style="margin-left: 630px;">Panier</a></li>
			</ul>
			<form class="navbar-form navbar-right">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Recherche">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit" style="height: 34px;">
							<i class="glyphicon glyphicon-search"></i>
						</button>
					</div>
				</div>
			</form> 
		  </div>
		</nav> 
		<div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-top: 52px;">
			  <!-- Indicators -->
			  <ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			  </ol>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" style="opacity: 0.8;">
				<div class="item active">
				  <img class="center-block" src="img/forza.jpg" alt="ronaldo"/>
				</div>

				<div class="item">
				  <img class="center-block" src="img/ronaldo.jpg" alt="assassin"/>
				</div>

				<div class="item">
				  <img class="center-block" src="img/assassin.jpg" alt="forza"/>
				</div>
			  </div>

			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left"></span>
				<span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#myCarousel" data-slide="next">
				<span class="glyphicon glyphicon-chevron-right"></span>
				<span class="sr-only">Next</span>
			  </a>
			</div>
			
			<div class="input-group" style="position: absolute;top: 360px;left: 432px;">
				<form method="post" action="nom_jeux_page1">
					<input type="text" class="form-control" name="nom" placeholder="Rechercher un jeu" style="display: inline-block;width: 456px;height:62px;font-size: 24px;" required>
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit" style="position: absolute;top: 0px;height: 62px;width: 47px;">
							<i class="glyphicon glyphicon-search"></i>
						</button>
					</div>
				</form>
			</div>
    </body>
</html>
	