
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="header.css">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
	</head>
    <body background="img/back-jeux.jpg" >	
		
		 <nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <a class="navbar-brand" href="accueil">MegaGame</a>
			</div>
			<ul class="nav navbar-nav" style='font-family: "Lucida Console", Monaco, monospace;'>
			  <li><a href="accueil">Accueil</a></li>
			  <li><a href="jeux_page1">Jeux</a></li>
			  <li><a href="ajout_jeu">Ajouter</a></li>
			  
			   <li><a href="panier_jeux" style="margin-left: 630px;">Panier</a></li>
			</ul>
			<form class="navbar-form navbar-right">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Recherche">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit" style="height: 34px;">
							<i class="glyphicon glyphicon-search"></i>
						</button>
					</div>
				</div>
			</form> 
		  </div>
		</nav> 
		<div class="img-mrace"><img src="img/m-race.png" class="img-responsive" alt="Cell" ></div> 
		
			
			<div class="rectangle2" id="content">

				<?php $count = 1; ?>
					<div class="container"><div class="row">

					<?php 
						if(!empty($jeux)){
						foreach ($jeux as $value){  ?>

					    		<div class="row"><div class="col-xs-12"><div class="div_p">
			    				
			    				<div class="nom_jeu_div"><p class="nom_jeux"><b><?php echo $value->Nom ?></b></p><hr></div>
			    				
			    				<div class="row"><div class="col-xs-6"><img class="" src=" <?php echo $value->Image ?>" alt="<?php echo $value->id ?>" style="padding-top: 10px;margin-left: 250px;margin-bottom: 20px;"></div><br>

			    				<div class="col-xs-6"><p class="prix_panier"><u>Prix</u>: <b><?php echo $value->Prix ?>€ </b></p><br>

			    				<div class="console">
			    				<?php if($value->PS4 >= 1){ ?>
			    					<div class="jeux_console_ps4"><img class="center-block" src="img/icone/ps4.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->XBOX_ONE >= 1){ ?>
			    					<div class="jeux_console_one"><img class="center-block" src="img/icone/one.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->SWITCH >= 1){ ?>
			    					<div class="jeux_console_ps4"><img class="center-block" src="img/icone/switch.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->XBOX_360 >= 1){ ?>
			    					<div class="jeux_console_one"><img class="center-block" src="img/icone/360.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->PC >= 1){ ?>
			    					<div class="jeux_console_ps4"><img class="center-block" src="img/icone/pc.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->PS3 >= 1){ ?>
			    					<div class="jeux_console_one"><img class="center-block" src="img/icone/ps3.png" alt="<?php echo $value->id ?>"></div>
			    				<?php }
			    				if($value->PC == 0 && $value->PS4 == 0 && $value->XBOX_ONE == 0 && $value->SWITCH == 0 && $value->XBOX_360 == 0 && $value->PS3  == 0 ){ ?>
			    					<div class="jeux_r"> </div>
			    				<?php } ?>
			    				</div><br>

			    				<p class="prix_panier"><u>Editeur</u>:<?php echo $value->Editeur ?></p>
			    				<p class="prix_panier"><u>Categorie</u>: <?php echo $value->Categorie ?></p>
			    				<p class="prix_panier"><u>Date de Sortie</u>:<?php echo $value->Date ?></p><br>
			    				
			    				<form action="panier_jeux" method="post" >
			    					<button class="bt_p" type="submit" name="id" value="<?php echo $value->id ?>" onClick="reply_click(this.id)">Acheter</button>
			    				</form>
			    				<form action="modifier_jeu" method="post" >
			    					<input type="hidden" name="id" value="<?php echo $value->id ?>">
			    					<button class="bt_p" type="submit">Modifier</button>
			    				</form>
			    				<form action="verif_supp_jeu" method="post">
			    					<button  class="bt_p" type="submit" name="id" value="<?php echo $value->id ?>" onClick="reply_click(this.id)">Supprimer</button>
			    				</form>
		    					</div></div></div></div></div>";

			    				<div class="console">
							<?php }
						}
						?>
					</div>
		</body>
</html>