<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
		<link rel="stylesheet" type="text/css" href="header.css">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
	</head>
    <body background="img/back-jeux.jpg" >	
		
		 <nav class="navbar navbar-inverse navbar-fixed-top">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <a class="navbar-brand" href="accueil">MegaGame</a>
			</div>
			<ul class="nav navbar-nav" style='font-family: "Lucida Console", Monaco, monospace;'>
			  <li><a href="accueil">Accueil</a></li>
			  <li><a href="jeux_page1">Jeux</a></li>
			  <li><a href="ajout_jeu">Ajouter</a></li>
			  
			   <li><a href="panier_jeux" style="margin-left: 630px;">Panier</a></li>
			</ul>
			<form class="navbar-form navbar-right">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Recherche">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit" style="height: 34px;">
							<i class="glyphicon glyphicon-search"></i>
						</button>
					</div>
				</div>
			</form> 
		  </div>
		</nav> 
		<div class="img-mario"><img src="img/mario.jpg" class="img-responsive" alt="Cell" ></div>
		<div class="rectangle" id="content">
			<p class="verif_jeu">Votre jeu a été supprimé</p>
		</div>
	</body>
</html>